# 函数

- [函数值](#函数值)
- [多返回值](#多返回值)
- [闭包](#闭包)
    - [捕获迭代变量](#捕获迭代变量)
    - [可变参数函数](#可变参数函数)
    - [defer](#defer)
        - [defer理解的注意点](#defer理解的注意点)
- [错误处理](#错误处理)
    - [错误传递](#错误传递)
    - [重新尝试](#重新尝试)
    - [输出错误信息并结束程序](#输出错误信息并结束程序)
    - [仅输出错误信息](#仅输出错误信息)
    - [忽略错误](#忽略错误)
    - [EOF](#eof)
    - [Panic](#panic)
    - [统一的错误处理](#统一的错误处理)
- [Recover](#recover)
- [自定义Error](#自定义error)

```golang
func name(parameter-list) (result-list) {
    body
}
```

- Go语言使用可变栈，栈的大小按需增加(初始时很小)。这使得我们使用递归时不必考虑溢出和安全问题
- **Go语言中不支持函数重载，也不支持默认参数**

## 函数值

- **在Go中，函数被看作第一类值（first-class values）**：函数像其他值一样，拥有类型，可以被赋值给其他变量，传递给函数，从函数返回
- 函数类型的零值是nil
- 函数值之间是不可比较的，也不能用函数值作为map的key

```golang
func square(n int) int { return n * n }
func negative(n int) int { return -n }
func product(m, n int) int { return m * n }

f := square
fmt.Println(f(3)) // "9"

f = negative
fmt.Println(f(3))     // "-3"
fmt.Printf("%T\n", f) // "func(int) int"

f = product // compile error: can't assign func(int, int) int to func(int) int
```

## 多返回值

- **Go语言的函数可以有多个返回值**

```golang
func findLinks(url string) ([]string, error) {
    resp, err := http.Get(url)
    if err != nil {
        return nil, err
    }
    if resp.StatusCode != http.StatusOK {
        resp.Body.Close()
        return nil, fmt.Errorf("getting %s: %s", url, resp.Status)
    }
    doc, err := html.Parse(resp.Body)
    resp.Body.Close()
    if err != nil {
        return nil, fmt.Errorf("parsing %s as HTML: %v", url, err)
    }
    return visit(nil, doc), nil
}
```

- 准确的变量名可以传达函数返回值的含义。尤其在返回值的类型都相同时

```golang
func Size(rect image.Rectangle) (width, height int)
func Split(path string) (dir, file string)
func HourMinSec(t time.Time) (hour, minute, second int)
```

- 而调用接受多参数的函数时，可以将一个返回多参数的函数作为该函数的参数

```golang
links, err := findLinks(url)
log.Println(links, err)

// 等价于
log.Println(findLinks(url))
```

- 如果一个函数所有的返回值都有显式的变量名，那么该函数的return语句可以省略操作数。这称之为bare return

```golang
func CountWordsAndImages(url string) (words, images int, err error) {
    // 在函数体的开启处，words和images被初始化为0，0
    resp, err := http.Get(url)
    if err != nil {
        // 相当于return 0, 0, err
        return
    }
    doc, err := html.Parse(resp.Body)
    resp.Body.Close()
    if err != nil {
        err = fmt.Errorf("parsing HTML: %s", err)
        // 相当于return 0, 0, err
         return
    }
    words, images = countWordsAndImages(doc)
    // 相当于return words, images, nil
    return
}
```

- **不能⽤容器对象接收多返回值。只能⽤多个变量，或 "_" 忽略**

```golang
func test() (int, int) {
    return 1, 2
}
func main() {
    // s := make([]int, 2)
    // s = test() // Error: multiple-value test() in single-value context
    x, _ := test()
    println(x)
}
```

## 闭包

- 匿名函数可以访问完整的词法环境（lexical environment），这意味着**在函数中定义的内部函数可以引用该函数的局部变量**

```golang
// squares返回一个匿名函数。
// 该匿名函数每次被调用时都会返回下一个数的平方。
func squares() func() int {
    var x int
    return func() int {
        x++
        return x * x
    }
}
func main() {
    f := squares()
    fmt.Println(f()) // "1"
    fmt.Println(f()) // "4"
    fmt.Println(f()) // "9"
    fmt.Println(f()) // "16"
}
```

### 捕获迭代变量

```golang
// 正确的代码
var rmdirs []func()
for _, d := range tempDirs() {
    dir := d // NOTE: necessary!
    os.MkdirAll(dir, 0755) // creates parent directories too
    rmdirs = append(rmdirs, func() {
        os.RemoveAll(dir)
    })
}
// ...do some work…
for _, rmdir := range rmdirs {
    rmdir() // clean up
}

// 错误的代码
var rmdirs []func()
for _, dir := range tempDirs() {
    os.MkdirAll(dir, 0755)
    rmdirs = append(rmdirs, func() {
        os.RemoveAll(dir) // NOTE: incorrect!
    })
}

// 正确写法2
for _, dir := range tempDirs() {
    dir := dir // declares inner dir, initialized to outer dir
    // ...
}
```

- 问题的原因在于循环变量的作用域。在上面的程序中，for循环语句引入了新的词法块，循环变量dir在这个词法块中被声明。在该循环中生成的所有函数值都共享相同的循环变量。
 **需要注意，函数值中记录的是循环变量的内存地址，而不是循环变量某一时刻的值**。以dir为例，后续的迭代会不断更新dir的值，当删除操作执行时，for循环已完成，
 dir中存储的值等于最后一次迭代的值。这意味着，每次对os.RemoveAll的调用删除的都是相同的目录。

### 可变参数函数

```golang
func sum(vals...int) int {
    total := 0
    for _, val := range vals {
        total += val
    }
    return total
}

fmt.Println(sum())           // "0"
fmt.Println(sum(3))          // "3"
fmt.Println(sum(1, 2, 3, 4)) // "10"
```

- 调用者隐式的创建一个数组，并将原始参数复制到数组中，再把**数组的一个切片作为参数传给被调函数**
- **如果原始参数已经是切片类型，只需在最后一个参数后加上省略符**

```golang
values := []int{1, 2, 3, 4}
fmt.Println(sum(values...)) // "10"
```

- 虽然在可变参数函数内部，...int 型参数的行为看起来很像切片类型，但实际上，**可变参数函数和以切片作为参数的函数是不同的**

```golang
func f(...int) {}
func g([]int) {}
fmt.Printf("%T\n", f) // "func(...int)"
fmt.Printf("%T\n", g) // "func([]int)"
```

### defer

- **首先defer后面跟的是函数调用**
- **直到包含该defer语句的函数执行完毕时，defer后的函数调用才会被执行**，不论包含defer语句的函数是通过return正常结束，还是由于panic导致的异常结束。
- **可以在一个函数中执行多条defer语句，它们的执行顺序与声明顺序相反**

```golang
func title(url string) error {
    resp, err := http.Get(url)
    if err != nil {
        return err
    }
    defer resp.Body.Close()
    ct := resp.Header.Get("Content-Type")
    if ct != "text/html" && !strings.HasPrefix(ct,"text/html;") {
        return fmt.Errorf("%s has type %s, not text/html",url, ct)
    }
    doc, err := html.Parse(resp.Body)
    if err != nil {
        return fmt.Errorf("parsing %s as HTML: %v", url,err)
    }
    // ...print doc's title element…
    return nil
}

package ioutil
func ReadFile(filename string) ([]byte, error) {
    f, err := os.Open(filename)
    if err != nil {
        return nil, err
    }
    defer f.Close()
    return ReadAll(f)
}

var mu sync.Mutex
var m = make(map[string]int)
func lookup(key string) int {
    mu.Lock()
    defer mu.Unlock()
    return m[key]
}
```

- 利用defer机制记录何时进入和退出函数

```golang
func bigSlowOperation() {
    // defer用于函数调用，trace()返回一个函数，必须再加上一个括号，表示函数调用
    defer trace("bigSlowOperation")() // don't forget the extra parentheses
    // ...lots of work…
    time.Sleep(10 * time.Second) // simulate slow
    operation by sleeping
}
func trace(msg string) func() {
    start := time.Now()
    log.Printf("enter %s", msg)
    return func() { 
        log.Printf("exit %s (%s)", msg,time.Since(start)) 
    }
}
```

#### defer理解的注意点

[golang的defer精析](https://studygolang.com/articles/742)

- golang中的return是用栈返回值的，并且不是一个原子操作
- 整个return过程，没有defer之前可以理解为：
    - 先把在栈中写一个值，这个值被会当作返回值。
    - 然后再调用RET指令返回。
- **defer的执行是被插入到return指令之前的，有了defer之后，就变成了 **赋值指令 + CALL defer指令 + RET指令**。
- 理解带defer的return xxx语句：
    - 返回值 = xxx
    - 调用defer函数
    - 空的return
- **所以如果要通过defer修改return xxx的值，返回值必须是一个具名返回值，并且在defer中修改具名返回值**

```golang
func f() (result int) {
    defer func() {
        result++
    }()
    return 0
}

// 返回的是1
func f() (result int) {
    result = 0 //return语句不是一条原子调用，return xxx其实是赋值＋RET指令 
    func() { //defer被插入到return之前执行，也就是赋返回值和RET指令之间 
        result++
    }()
    return
}
```

```golang
func f() (r int) {
    t := 5
    defer func() {
        t = t + 5
    }()
    return t
}

// 返回的是5
func f() (r int) {
    t := 5
    r = t //赋值指令
    func() { //defer被插入到赋值与返回之间执行，这个例子中返回值r没被修改过 
        t = t + 5
    }
    return //空的return指令
}
```

```golang

func f() (r int) {
    defer func(r int) {
        r = r + 5
    }(r)
    return 1
}

// 返回的是1
func f() (r int) {
    r = 1 //给返回值赋值
    func(r int) { //这里改的r是传值传进去的r，不会改变要返回的那个r值 
        r = r + 5
    }(r)
    return //空的return
}
```

- **defer调用的参数会立刻生成**，但是在上层函数返回前函数都不会被调用

```golang
func testDefer2() {
    a := 1
    // defer虽然会在函数才会返回，但是调用的参数实际上是在定义时就生成的
    defer func(a int) {
        a++
        fmt.Println("defer:", a)
    }(a)
    a = 2
    fmt.Println(a)
}

//输出
//2
//defer: 2
```

- **延迟的函数调用被压入一个栈中。当函数返回时， 会按照后进先出的顺序调用被延迟的函数调用**

```golang
func testDefer3() {
    fmt.Println("counting")

    for i := 0; i < 3; i++ {
        defer fmt.Println(i)
    }

    fmt.Println("done")
}

testDefer3()
//counting
//done
2
1
0
```

## 错误处理

### 错误传递

- 函数中某个子程序的失败，会变成该函数的失败
- 有些错误则要将错误包装再返回，被调函数f(x)会将调用信息和参数信息作为发生错误时的上下文放在错误信息中并返回给调用者，调用者需要添加一些错误信息中不包含的信息，比如添加url到html.Parse返回的错误中

```golang
resp, err := http.Get(url)
if err != nil{
    return nil, err
}

// 包装上下文
doc, err := html.Parse(resp.Body)
resp.Body.Close()
if err != nil {
    return nil, fmt.Errorf("parsing %s as HTML: %v", url,err)
}
```

### 重新尝试

- 如果错误的发生是偶然的，或由不可预知的问题导致的。一个明智的选择是重新尝试失败的作。
- **在重试时，我们需要限制重试的时间间隔或重试的次数，防止无限制的重试。**

```golang
func WaitForServer(url string) error {
    const timeout = 1 * time.Minute
    deadline := time.Now().Add(timeout)
    for tries := 0; time.Now().Before(deadline); tries++ {
        _, err := http.Head(url)
        if err == nil {
            return nil // success
        }
        log.Printf("server not responding (%s);retrying…", err)
        time.Sleep(time.Second << uint(tries)) // exponential back-off
    }
    return fmt.Errorf("server %s failed to respond after %s", url, timeout)
}
```

### 输出错误信息并结束程序

- 这种策略只应在main中执行。对库函数而言，应仅向上传播错误
- 调用log.Fatalf可以更简洁的代码达到与上文相同的效果。log中的所有函数，都默认会在错误信息之前输出时间信

```golang
// (In function main.)
if err := WaitForServer(url); err != nil {
    fmt.Fprintf(os.Stderr, "Site is down: %v\n", err)
    os.Exit(1)
}
```

### 仅输出错误信息

- 有时，我们只需要输出错误信息就足够了，不需要中断程序的运行
- 我们可以通过log包提供函数或者标准错误流输出错误信息

```golang
if err := Ping(); err != nil {
    log.Printf("ping failed: %v; networking disabled",err)
}

if err := Ping(); err != nil {
    fmt.Fprintf(os.Stderr, "ping failed: %v; networking disabled\n", err)
}
```

### 忽略错误

```golang
dir, err := ioutil.TempDir("", "scratch")
if err != nil {
    return fmt.Errorf("failed to create temp dir: %v",err)
}
// ...use temp dir…
os.RemoveAll(dir) // ignore errors; $TMPDIR is cleaned periodically
```

- **在Go中，检查某个子函数是否失败后，我们通常将处理失败的逻辑代码放在处理成功的代码之前**
- **如果某个错误会导致函数返回，那么成功时的逻辑代码不应放在else语句块中，而应直接放在函数体中。**
- **Go中大部分函数的代码结构几乎相同，首先是一系列的初始检查，防止错误发生，之后是函数的实际逻辑**

### EOF

- io包保证任何由文件结束引起的读取失败都返回同一个错误——io.EOF

```golang
package io

import "errors"

// EOF is the error returned by Read when no more input is available.
var EOF = errors.New("EOF")

in := bufio.NewReader(os.Stdin)
for {
    r, _, err := in.ReadRune()
    if err == io.EOF {
        break // finished reading
    }
    if err != nil {
        return fmt.Errorf("read failed:%v", err)
    }
    // ...use r…
}
```

### Panic

- 一般而言，当panic异常发生时，程序会中断运行，并立即执行在该goroutine中被延迟的函数（defer 机制）。随后，程序崩溃并输出日志信息。日志信息包括panic value和函数调用的堆栈跟踪信息。panic value通常是某种错误信息。对于每个goroutine，日志信息中都会有与之相对的，发生panic时的函数调用堆栈跟踪信息
- 由于panic会引起程序的崩溃，因此panic一般用于严重错误，如程序内部的逻辑不一致。**对于大部分程序的漏洞，我们应该使用Go提供的错误机制，而不是panic，尽量避免程序的崩溃。**
- **在Go的panic机制中，延迟函数的调用在释放堆栈信息之前**

```golang
func f(x int) {
    fmt.Printf("f(%d)\n", x+0/x) // panics if x == 0
    defer fmt.Printf("defer %d\n", x)
    f(x - 1)
}

func main() {
    defer printStack()
    f(3)
}

func printStack() {
    var buf [4096]byte
    n := runtime.Stack(buf[:], false)
    os.Stdout.Write(buf[:n])
}
```

### 统一的错误处理

- golang的错误处理方式容易导致错误处理代码的冗余，对于这种情况是我们通过复用检测函数来减少类似的代码

```golang
func init() {
    http.HandleFunc("/view", viewRecord)
}

// 最原始的方法在每个地方处理错误
func viewRecord(w http.ResponseWriter, r *http.Request) {
    c := appengine.NewContext(r)
    key := datastore.NewKey(c, "Record", r.FormValue("id"), 0, nil)
    record := new(Record)
    if err := datastore.Get(c, key, record); err != nil {
        http.Error(w, err.Error(), 500)
        return
    }
    if err := viewTemplate.Execute(w, record); err != nil {
        http.Error(w, err.Error(), 500)
    }
}

```

```golang
// 将http接口包装一层
func init() {
    http.Handle("/view", appHandler(viewRecord))
}

type appHandler func(http.ResponseWriter, *http.Request) error

func (fn appHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
    if err := fn(w, r); err != nil {
        http.Error(w, err.Error(), 500)
    }
}

func viewRecord(w http.ResponseWriter, r *http.Request) error {
    c := appengine.NewContext(r)
    key := datastore.NewKey(c, "Record", r.FormValue("id"), 0, nil)
    record := new(Record)
    if err := datastore.Get(c, key, record); err != nil {
        return err
    }
    return viewTemplate.Execute(w, record)
}
```

```golang
// 自定义错误类型方便扩展
type appError struct {
    Error   error
    Message string
    Code    int
}

type appHandler func(http.ResponseWriter, *http.Request) *appError

func (fn appHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
    if e := fn(w, r); e != nil { // e is *appError, not os.Error.
        c := appengine.NewContext(r)
        c.Errorf("%v", e.Error)
        http.Error(w, e.Message, e.Code)
    }
}

func viewRecord(w http.ResponseWriter, r *http.Request) *appError {
    c := appengine.NewContext(r)
    key := datastore.NewKey(c, "Record", r.FormValue("id"), 0, nil)
    record := new(Record)
    if err := datastore.Get(c, key, record); err != nil {
        return &appError{err, "Record not found", 404}
    }
    if err := viewTemplate.Execute(w, record); err != nil {
        return &appError{err, "Can't display record", 500}
    }
    return nil
}
```

## Recover

- 通常来说，不应该对panic异常做任何处理，但有时，也许我们可以从异常中恢复，至少我们可以在程序崩溃前，做一些操作,比如关闭连接等
- 如果在deferred函数中调用了内置函数recover，并且定义该defer语句的函数发生了panic异常，recover会使程序从panic中恢复，并返回panic value。导致panic异常的函数不会继续运行，但能正常返回。在未发生panic时调用recover，recover会返回nil

```golang
func Parse(input string) (s *Syntax, err error) {
    defer func() {
        if p := recover(); p != nil {
            err = fmt.Errorf("internal error: %v", p)
        }
    }()
    // ...parser...
}
```

- **不加区分的恢复所有的panic异常，不是可取的做法**；因为在panic之后，无法保证包级变量的状态仍然和我们预期一致
- **安全的做法是有选择性的recover**。换句话说，只恢复应该被恢复的panic异常，**为了标识某个panic是否应该被恢复，我们可以将panic value设置成特殊类型。在recover时对panic value进行检查，如果发现panic value是特殊类型，就将这个panic作为errror处理，如果不是，则按照正常的panic进行处理**

```golang
func soleTitle(doc *html.Node) (title string, err error) {
    type bailout struct{}
    defer func() {
        switch p := recover(); p {
        case nil:       // no panic
        case bailout{}: // "expected" panic
            err = fmt.Errorf("multiple title elements")
        default:
            panic(p) // unexpected panic; carry on panicking
        }
    }()
    // Bail out of recursion if we find more than one nonempty title.
    forEachNode(doc, func(n *html.Node) {
        if n.Type == html.ElementNode && n.Data == "title" &&
            n.FirstChild != nil {
            if title != "" {
                panic(bailout{}) // multiple titleelements
            }
            title = n.FirstChild.Data
        }
    }, nil)
    if title == "" {
        return "", fmt.Errorf("no title element")
    }
    return title, nil
}
```

## 自定义Error

- **error是一个interface，所以在实现自己的包的时候，通过定义实现此接口的结构，我们就可以实现自己的错误定义**

```golang
type SyntaxError struct {
    msg    string // 错误描述
    Offset int64  // 错误发生的位置
}

func (e *SyntaxError) Error() string { return e.msg }
```

- **处理错误时可以通过类型断言获取错误类型，从而细化错误的处理**

```golang
if err := dec.Decode(&val); err != nil {
    if serr, ok := err.(*json.SyntaxError); ok {
        line, col := findLine(f, serr.Offset)
        return fmt.Errorf("%s:%d:%d: %v", f.Name(), line, col, err)
    }
    return err
}
```

- **函数返回自定义错误时，返回值推荐设置为error类型，而非自定义错误类型**
- **特别需要注意的是不应预声明自定义错误类型的变量**(接口只有类型和值都为nil,接口类型才为nil)

```golang
func Decode() *SyntaxError { // 错误，将可能导致上层调用者err!=nil的判断永远为true。
    var err *SyntaxError     // 预声明错误变量
    if 出错条件 {
        err = &SyntaxError{}
    }
    return err               // 错误，err永远等于非nil，导致上层调用者err!=nil的判断始终为true
}
```

- **更复杂的错误**

```golang
package net

type Error interface {
    error
    Timeout() bool   // Is the error a timeout?
    Temporary() bool // Is the error temporary?
}

// 如果一个网络发生临时性错误，那么将会sleep 1秒之后重试
if nerr, ok := err.(net.Error); ok && nerr.Temporary() {
    time.Sleep(1e9)
    continue
}
if err != nil {
    log.Fatal(err)
}
```
